[package]

name = "tls-json-parser"
version = "0.0.1"
authors = [ "Johannes Schleger <johannes.schleger@tum.de>" ]


[dependencies]
tls-parser = "0.4.0"
serde_json = "1.0"
nom = "*"
rustc-serialize = "0.3"
base64 = "~0.5.0"
